language: python

python:
  - 3.6.8
  - 3.7

services:
  - docker

#before_script:
#  - docker run --name elastic -p 0.0.0.0:9200:9200 -d elasticsearch:6.5.4

script:
  - docker build -t markov-chain-text-editor .